//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DosCuerdas.Modelo
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cita
    {
        public int IDCITA { get; set; }
        public string HORA_CITA { get; set; }
        public double DURACION { get; set; }
        public string ESTADO { get; set; }
        public System.DateTime FECHACITA { get; set; }
        public string Observaciones { get; set; }
        public int Id_Usuario { get; set; }
        public int Id_Profesor { get; set; }
        public int Id_Estudiante { get; set; }
    
        public virtual Estudiantes Estudiantes { get; set; }
        public virtual Profesores Profesores { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
